name = "youtube-downloader"
main = "src/worker.js"
compatibility_date = "2024-09-24"

[vars]
ALLOWED_ORIGINS = "https://sebagutierrezf.github.io"
CLOUDFLARE_API_TOKEN = "qv5itRdEn4BVmyG1094ve5sJ_fxDN9kcl-cpaJsi"
CLOUDFLARE_ACCOUNT_ID = "fccc15afa453ea68debf4a976cb3627e"

# Las variables secretas se configurar√°n usando wrangler secret
# npx wrangler secret put AIzaSyA-63NUex9DDsLfotTHDUeiVmI5cDs_x_c
# npx wrangler secret put qv5itRdEn4BVmyG1094ve5sJ_fxDN9kcl-cpaJsi

[[rules]]
type = "ESModule"
globs = ["**/*.js"]